openapi: 3.0.0
info:
  title: Auth Service API
  description: Authentication and identity validation API for SpaceFlow platform
  version: 1.0.0
servers:
  - url: /api/v1
    description: Auth Service API v1

paths:
  /authenticate:
    post:
      summary: Authenticate identity
      description: Authenticates an identity using credentials and returns confirmation with role
      operationId: authenticate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticationRequest'
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponse'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /validate:
    post:
      summary: Validate identity
      description: Validates an existing identity and returns associated role
      operationId: validate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidationRequest'
      responses:
        '200':
          description: Identity validated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResponse'
        '401':
          description: Identity invalid or not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    AuthenticationRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    AuthenticationResponse:
      type: object
      required:
        - identityReference
        - role
      properties:
        identityReference:
          type: string
        role:
          type: string

    ValidationRequest:
      type: object
      required:
        - identityReference
      properties:
        identityReference:
          type: string

    ValidationResponse:
      type: object
      required:
        - valid
        - identityReference
        - role
      properties:
        valid:
          type: boolean
        identityReference:
          type: string
        role:
          type: string

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
        message:
          type: string
